USE DATABASE NZ_VEHICLE_THEFT;
USE SCHEMA STAGING;

-- Confirm rows loaded
SELECT COUNT(*) AS rows_loaded
FROM STG_STOLEN_VEHICLES;

-- Peek at a few rows
SELECT * 
FROM STG_STOLEN_VEHICLES
LIMIT 10;
